FROM byuoitav/arm32v6-alpine
LABEL Brayden Winterton <brayden_winterton@byu.edu>

ARG NAME
ENV name=${NAME}

COPY ${name}-arm ${name}-arm
COPY version.txt version.txt

# add any required files/folders here
COPY autoclave-dist autoclave-dist

ENTRYPOINT ./${name}-arm